### ISSUE TITLE
DLNA support

### ISSUE THREAD

**Issue by gabriellluz** [EsTass/phpmediaserver#1]
Hi there.

I think your tool is really interesting and it might be a great Plex Media Server replacement.
It'd be nice if you could add DLNA support.

**Comment by EsTass** [comment]
Thanks.
I do not know how dlna works, I'll look if a simple way to do it is possible and add

**Comment by EsTass** [comment]
Test and comment, for now is only a simple categories list with last elements but working on paged lists and more folders like frontal page.
The first problem is make compatible with more TVs and players and testers needed.

**Comment by gabriellluz** [comment]
Ok. I'll test it.
