### ISSUE TITLE
 logo proposal for phpmediaserver

### ISSUE THREAD

**Issue by leonardoderoy** [EsTass/phpmediaserver#2]
Hello! @EsTass

I'm a graphic designer and I like to support your project because I believe a good logo that reflects your project at its best can help the project publicity and trustability, also i'm an open source enthusiast. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Leonardo Deroy

Graphic Designer

**Comment by EsTass** [comment]
Hi Leonard!

Sure!, a logo is really need and my abilities with design are a least 0.
Help will be welcome, thanks!

**Comment by leonardoderoy** [comment]
you could provide me with all the information about your project and what it is about.
Thank you @EsTass

**Comment by EsTass** [comment]
web media server, you can read all the info in frontal page. Have dark theme, you can use `imgs/bg.png`as base for colors if needed.

**Comment by leonardoderoy** [comment]
Hellow @EsTass
Soon I will be uploading the proposal

**Comment by leonardoderoy** [comment]
Hellow @EsTass  here is my initial design, remember that it is only a sketch and you can suggest changes. I hope you like it.

**Comment by leonardoderoy** [comment]
![image](https://user-images.githubusercontent.com/40496274/42119956-cb75564a-7be0-11e8-88c7-12d42a5d9b71.png)

**Comment by EsTass** [comment]
Very good job, I think the 15 fits with the colors. What do you think?
With the transparent background I can use it in the forms easily.

Thanks for the work.

**Comment by leonardoderoy** [comment]
yes i agree with your pick, can i submit a pull request?

**Comment by EsTass** [comment]
Push `imgs/logo.png` I'll change in html in next patch

**Comment by leonardoderoy** [comment]
i have just made my pull request #3 if you want to change anything i can do that @EsTass

**Comment by EsTass** [comment]
Added and again thanks!

**Comment by leonardoderoy** [comment]
![1](https://user-images.githubusercontent.com/40496274/42296933-20d7668c-7fc9-11e8-96a0-a9abdaaa071a.png)
![2](https://user-images.githubusercontent.com/40496274/42296937-2995deb6-7fc9-11e8-97ae-07a3ca20c059.png)
![3 4](https://user-images.githubusercontent.com/40496274/42296944-3e8842be-7fc9-11e8-9b07-405c5745d955.png)
![4 1](https://user-images.githubusercontent.com/40496274/42296949-4935f88c-7fc9-11e8-84db-7e035bbc731a.png)
![5](https://user-images.githubusercontent.com/40496274/42296957-4d13e9fa-7fc9-11e8-9a7b-eaca8fc0962f.png)
![6](https://user-images.githubusercontent.com/40496274/42296961-4f27fcea-7fc9-11e8-928b-bfa8674b600f.png)
![7](https://user-images.githubusercontent.com/40496274/42296962-501f6a3e-7fc9-11e8-92ff-d3e600f60fb3.png)
![8](https://user-images.githubusercontent.com/40496274/42296965-52685cf6-7fc9-11e8-814c-f397afc3c667.png)
![9](https://user-images.githubusercontent.com/40496274/42296967-564c4fc6-7fc9-11e8-9b89-a1173c29b0e0.png)
glad you liked it

**Comment by EsTass** [comment]
Can you make a _icon_ from green model? same with and height, its for favicon and icon in kodi plugin.
Thanks for help @leonardoderoy !
