### ISSUE TITLE
Error pymediaident.py

### ISSUE THREAD

**Issue by gabriellluz** [EsTass/phpmediaserver#4]
Error when using:
~$ pymediaident.py -h
I get:

-bash: /usr/bin/pymediaident.py: /bin/python: bad interpreter: No such file or directory

Hi. I still owe you the DLNA test. I'll test it in the next few days because I have a brand new Ubuntu Server.

**Comment by EsTass** [comment]
check python installed (at least 3), if installed try removing first line of script (my fault, not needed): `#!/bin/python` or redownload, its fixed
Alternative: use `python pymediaident.py`
