### ISSUE TITLE
HTTP/1.1 401 Unauthorized

### ISSUE THREAD

**Issue by Zoe8338** [EsTass/phpmediaserver#6]
I just unzipped the folder on my web server and tried to access it. It just shows this error.
I have PHP 7.2

**Comment by EsTass** [comment]
Set user:group on unzipped files same as apache server, http:http for apache on arch for example.

**Comment by Zoe8338** [comment]
> .

I'm not sure what you mean.

**Comment by EsTass** [comment]
Apache server need to have access to php files, setting user:group grants apache and php access to files.

If you are accessing from LAN and your IP range not in list need to add it to core/functions.php:97

`$VALID_IPs = array( 
            '192.168.',
            '10.0.',
        );`

Message "HTTP/1.1 401 Unauthorized" in text mode as result means IP not in valid list.

**Comment by Zoe8338** [comment]
> Apache server need to have access to php files, setting user:group grants apache and php access to files.
> 
> If you are accessing from LAN and your IP range not in list need to add it to core/functions.php:97
> 
> `$VALID_IPs = array( '192.168.', '10.0.', );`
> 
> Message "HTTP/1.1 401 Unauthorized" in text mode as result means IP not in valid list.

I'm not accessing from LAN. It's on a third party server which I can only control the files I put into it.

**Comment by EsTass** [comment]
Disable "Country Access Limit" on config:

`//Countrys allowed (http://www.geoplugin.net)`
`define( 'O_COUNTRYALLOWED', array( '' ) );`

to

`//Countrys allowed (http://www.geoplugin.net)`
`define( 'O_COUNTRYALLOWED', FALSE );`

Or set your country to limit access to only that country.

EDIT: Probably your IP already in BAN list, need to reset database file (remove and copy again from zip) or delete IP from "Bans" table and Add to "Whitelist" table, add https://www.phpliteadmin.org/ to server, configure to have access to DB file and edit IPs on tables "Bans" and "Whitelist".

**Comment by EsTass** [comment]
Added a fix for "IP Country Filter" disabled if not countrys in list or no list.

Thanks for testing :)
